### ISSUE TITLE
linux_shell_zsh

### ISSUE THREAD

**Issue by lingyiba** [yaoniplan/note#11]
* `ctrl + shift + e` # If your zsh is't work, then please use hotkey `ctrl + shift + e` to exit i3 in your i3wm.(After exiting i3, you need input your password to start i3)
* https://github.com/yaoniplan/note/blob/bc06b4758dc4a4e990af530a3b773433dacf7566/journals/2022_08_25.md

**Comment by yaoniplan** [comment]
Ok, add it. #done
