### ISSUE TITLE
add_python_book

### ISSUE THREAD

**Issue by lingyiba** [yaoniplan/note#13]
![IMG_20220918_221710_046](https://user-images.githubusercontent.com/111936474/190911660-7e003ab7-2443-44fb-aa88-70006db63562.jpg)
1. http://www.ituring.com.cn/book/1863
2. https://docs.python.org/
3. https://github.com/yidao620c/python3-cookbook
4. https://bit.ly/2KxFYvD

**Comment by yaoniplan** [comment]
https://www.aliyundrive.com/s/XmEsDZd9HoT # 1 and 4 had recorded.
