### ISSUE TITLE
README.md_improve_deadline_2022-09-24_23:59:59

### ISSUE THREAD

**Issue by yaoniplan** [yaoniplan/note#14]
# In principle
* `less is more` 

# Steps 
1. `remove subtitle "Changelog"` # We may update here.
2. `change "Table of content" into tables of markdown` # We can get it faster.
3. `merge tables of markdown` # Less is more.
4. `rename name of tables` # Make it easier.
5. `remove subtitle "Yaoniplan", "Disclaimer"` # We can watch it in "pages/README_2022-09-18_backup.md" path.
6. `move subtitle "record" from "README.md" to "Issues"`# We can watch it in here. 
7. `show something and hide something` # We can get it faster, too.

**Comment by lingyiba** [comment]
You can close it.

**Comment by yaoniplan** [comment]
Ok, I'll close it.
