### ISSUE TITLE
pages/future_seldom_website_add

### ISSUE THREAD

**Issue by lingyiba** [yaoniplan/note#15]
* 18comic # There are three lines in china.
    1. https://jmcomic2.moe/?shunt=1
    2. https://jmcomic2.moe/?shunt=2
    3. https://jmcomic2.moe/?shunt=3
* ***References***
* [禁漫天堂發布頁](https://jmcomic.bet/)

**Comment by yaoniplan** [comment]
https://github.com/yaoniplan/note/blob/main/pages/future.md #done
