### ISSUE TITLE
methodsAboutTooth

### ISSUE THREAD

**Issue by lingyiba** [yaoniplan/note#17]
https://m.youtube.com/watch?v=0Bdnq36GAZ0
copied from the open source
一、選牙刷要點：
  1.	軟毛
     i.	目的：不讓牙齒、牙肉受傷
     ii.測試方式：抵在手臂內側用力的刷，會痛就是太硬
  2.	頭小
     i.	頭太大就不易刷到嘴巴內側狹窄處
     ii.選擇方式：刷頭和第二節小指長度差不多，或刷頭約略覆蓋2又1/2的牙齒
  3.	柄薄
     i.	太厚阻礙清潔
     ii.用前兩個準則篩選後，再挑選握柄最薄的

二、刷牙要點：
  1.	牙齒有五面都要清潔到
  2.	口訣：輕、小、多、順序
     i.	輕輕刷，判斷依據，用平常刷牙的力道，將牙刷抵在指甲上，若指甲泛白，就是太大力。
     ii.小範圍的刷：一次以兩顆牙齒為單位刷
     iii.多刷幾下：一處至少15下
     iv.刷牙一定要有順序，否則會亂掉、漏刷

三、刷牙三大盲點（三個常見沒有清潔乾淨的地方）：
  1.	最後一顆牙齒（大臼齒）的內側（靠舌頭處）＆外側（靠臉頰處）
  2.	小臼齒跟門牙
  3.	牙縫處：牙刷一定刷不到，必須用牙線、或牙間刷等輔助品

四、三大錯誤觀念：
  1.	以為「裝了假牙就不會蛀牙（齵齒）」	
	品質不好的假牙更容易蛀
  2.	以為「使用牙線，會害我牙齦萎縮」
	正確使用牙線、或牙間刷，反而會讓你預防牙齦萎縮、或牙齒敏感
  3.	以為「牙齒不會痛就不用看牙醫」
     i.	通常蛀牙初期不會痛，等到會痛都已經蛀的非常大了，非常接近牙齒的神經和血管，那個時候就必須抽神經、根管治療了。
     ii.半年要做一次牙齒定檢

**Comment by yaoniplan** [comment]
Add it to https://github.com/yaoniplan/note/blob/057fb21cc3458a66401c4ce1b4276f5cd82f9fea/journals/2023_01_08.md#choose-a-toothbrush
