### ISSUE TITLE
methodsAboutSpine

### ISSUE THREAD

**Issue by lingyiba** [yaoniplan/note#18]
https://m.youtube.com/watch?v=udAhvg1ANLM
00:00 7月16日影片
01:06 視力退化？原來頸椎出問題
05:26 上班族這一招舒緩眼部疲勞 
08:16 眼睛酸痛時  這4個動作幫你舒緩壓力 
13:36 看手機用這個姿勢  優雅又健康
18:32 視差大影響頸椎  矯正有方法
21:14 保護頸椎  避免做哪些事？

**Comment by yaoniplan** [comment]
https://github.com/yaoniplan/note/tree/master/journals/2023-04-24.md # done
