### ISSUE TITLE
add to ac.txt

### ISSUE THREAD

**Issue by lingyiba** [yaoniplan/note#3]
![1-34,39-54](https://user-images.githubusercontent.com/111936474/186941179-96d23445-41f8-4a56-b708-68eec7e68c75.jpg)
![55-88,93-126,131-143](https://user-images.githubusercontent.com/111936474/186941240-cdca5cc4-bd5d-4e76-a999-d9f393826bb7.jpg)
![144-177,182-200](https://user-images.githubusercontent.com/111936474/186941201-38a8ae25-4bd0-433f-9830-3db5033580b8.jpg)

**Comment by yaoniplan** [comment]
ok,add comics to ac.txt.(done)
