### ISSUE TITLE
linux_time

### ISSUE THREAD

**Issue by lingyiba** [yaoniplan/note#9]
* `sudo date -s "2022-09-14 09:33:30"`
* `sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime` # If date command is't work, then you can set your zone in your country.
* https://github.com/yaoniplan/note/blob/1826692eac211224a1eac27141577a69adb1c765/journals/2022_08_22.md

**Comment by yaoniplan** [comment]
Ok, add it into "journals/2022-08-22". #done
